#!/bin/bash

reverse(){
    input=$1
    len=${#input}
    for (( i=$len-1; i>=0; i-- ))
    do 
        reverse="$reverse${input:$i:1}"
    done
    
    echo $reverse
}

isPalind(){
    stringInput=$1
    returnedFromReverse=$(reverse $stringInput)
    if [ $returnedFromReverse != $stringInput ];
    then
        return 1
    else
        return 0     
    fi
}

feed(){
    file=$1
    if [ -f $file ]
    echo -e "=====\nFile: $file" >> output.palindrome
    flag=0
    then
        exec<$file
        while read line; do
            for word in $line; do
                wd=${word//;}
                wd2=${wd//.}
                isPalind $wd2
                if [[ $? -eq 0 ]];
                then
                    flag=1
                    echo -e $wd2 >> output.palindrome
                fi
            done
        done
    fi
    if [ $flag -eq 0 ]; then
        echo -e "No Palindromes in file!" >> output.palindrome
    fi
}

echo -e "Palindromes Found:" > output.palindrome

for item in $*
do
    feed $item
done